Repository SOS-RS/backend, pull requests merged in 2024-05, with the labels that each got.

#52 README.md 2.0 - readme mais bonito e organizado
  README.md
Labels: quality-of-life

#50 Add MIT license
  LICENSE
Labels: waiting-to-be-merged

#42 Quality of life: implement some quality of life updates reg Docker
  Dockerfile
  docker-compose.dev.yml
  tsconfig.json
Labels: waiting-approvals, quality-of-life

#48 Add formatting and linting checks to CI
  .github/workflows/ci.yml
  package.json
Labels: waiting-to-be-merged, ci

#94 Release 0.0.1
  .github/workflows/ci.yml
  .github/workflows/pull_request_template.md
  Dockerfile
  README.md
  docker-compose.dev.yml
  package.json
  prisma/migrations/20240512005246_/migration.sql
  prisma/schema.prisma
  src/decorators/UserDecorator/user.decorator.ts
  src/guards/apply-user.guard.ts
  src/guards/utils.ts
  src/shelter/ShelterSearch.ts
  src/shelter/shelter.controller.ts
  src/shelter/shelter.service.ts
  src/shelter/types/search.types.ts
  src/shelter/types/types.ts
  src/utils/utils.ts
  tsconfig.json
Labels: release

#123 Gitignore .nx
  .gitignore
Labels: can-merge

#124 Update readme with run instructions
  README.md
Labels: enhancement, can-merge

#155 fix: use correct status code(201) when create new entry on database
  src/partners/partners.controller.ts
Labels: enhancement

#154 test: cover getMany and create for partners entity
  src/partners/partners.controller.spec.ts
  src/partners/partners.service.spec.ts
Labels: enhancement

#149 feat: add min node version to install dependencies
  package.json
Labels: enhancement

#159 test: cover the whole session controler and service use cases
  src/sessions/sessions.controller.spec.ts
  src/sessions/sessions.service.spec.ts
Labels: waiting-business-requirements

#150 feat: add multi option for priority queryParam
  src/shelter/ShelterSearch.ts
  src/shelter/types/search.types.ts
Labels: enhancement
